// <auto-generated />
using System;
using Micklek.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Micklek.API.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20190125163737_addTableOrderLines")]
    partial class addTableOrderLines
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.1-servicing-10028");

            modelBuilder.Entity("Micklek.API.Models.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.Property<string>("PhotoUrl");

                    b.Property<float>("Price");

                    b.HasKey("Id");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("Micklek.API.Models.OrderHeader", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ClientCell");

                    b.Property<string>("ClientEmail");

                    b.Property<string>("ClientName");

                    b.Property<string>("ClientRemarks");

                    b.Property<DateTime>("DateCreation");

                    b.Property<DateTime>("DateTarget");

                    b.Property<int>("NumberOfItems");

                    b.Property<float>("TotalPrice");

                    b.HasKey("Id");

                    b.ToTable("OrderHeaders");
                });

            modelBuilder.Entity("Micklek.API.Models.OrderLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Amount");

                    b.Property<int>("ItemId");

                    b.Property<int>("LineNumber");

                    b.Property<int>("OrderId");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.ToTable("OrderLines");
                });

            modelBuilder.Entity("Micklek.API.Models.Value", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Values");
                });

            modelBuilder.Entity("Micklek.API.Models.OrderLine", b =>
                {
                    b.HasOne("Micklek.API.Models.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
